<?php
// Start output buffering
ob_start();

// Include necessary files and set up variables
include("../includes/db.php");
require("../vendor/autoload.php");

$cid = $_GET['cid'];
$sname = $_GET['sname'];
$score = $_GET['score'];
$tscore = $_GET['tscore'];

$sql = "SELECT * FROM `users`";
$result = mysqli_query($conn, $sql);
if(mysqli_num_rows($result) > 0){
    $row = mysqli_fetch_assoc($result);
    $fname = $row['first_name'];
    $lname = $row['last_name'];
    $email = $row['email'];

    // Generate HTML content
    $html = '<div class="container">
        <div class="head" style="justify-content:center;align-items:center;text-align:center">
        <h1 style="color:#2979FF;font-weight:1000"><i>SchoolMate</i></h1>
        <p>Online School Management System</p>
        </div>
        <div class="content">
        <hr>
            <div class="text" style="display:flex;padding-left:50px">
            <h3>Name:</h3>
            <p style="margin-left: 10px;margin-top: 20px">'.$fname.' '.$lname.'</p>
            </div>
            <hr>
            <div class="text" style="display:flex;padding-left:50px">
                <h3>Email:</h3>
                <p style="margin-left: 10px;margin-top: 20px">'.$email.'</p>
            </div>
            <hr>
            <div class="text" style="display:flex;padding-left:50px">
                <h3>Class:</h3>
                <p style="margin-left: 10px;margin-top: 20px">'.$cid.'</p>
            </div>
            <hr>
            <div class="text" style="display:flex;padding-left:50px">
                <h3>Subject:</h3>
                <p style="margin-left: 10px;margin-top: 20px">'.$sname.'</p>
                </div>
                <hr>
                <div class="text" style="display:flex;padding-left:50px">
                <h3>Total Score: '.$score.'/'.$tscore.'</h3>
                <p style="margin-left: 10px;margin-top: 20px">
                    
                </p>
                </div>
                <hr>
                <div class="text" style="display:flex;padding-left:50px">
                <h3 class="msg"> ';
                
                if($score>=($tscore*0.5)){
                    $html.= "Congratulations! You Passed the Test:)";
                }
                else{
                    $html.= "Study more! You Failed the Test:(";
                }

               $html.= '</h3>
               </div>
            <hr>
    
            </div>
    </div>';
    // echo $html;

    // Output buffering ends before PDF generation
    ob_end_clean();

    // PDF generation code starts
    $mpdf = new \Mpdf\Mpdf();
    $mpdf->WriteHTML($html);
    $mpdf->Output("Result.pdf", "D"); // there are more para like D- D for downloading the pdf- Force download the PDF

} else {
    // Handle case where no data is found
    echo '<h1>Data Not Found</h1>';
}
?>

<!-- explanation -->

<!-- used mpdf library to download pdf - pass your data in html format and through D parameter in output function, yopu can download pdf directly -->

<!-- ob_start() is a PHP function that turns on output buffering. When output buffering is active, instead of immediately sending output (like HTML, text, etc.) to the browser as it's generated by your PHP script, the output is stored internally in a buffer. This means that the output is not sent to the browser immediately but rather held in memory until you decide to do something with it.
 -->

<!-- 
 ob_end_clean() is another PHP function related to output buffering. It stops output buffering and discards the contents of the output buffer without sending it to the browser. This function is particularly useful if you want to clear the buffer without sending its contents to the client (browser). -->


<!-- 
everything between ob_start() and ob_end_clean() will not be sent to the browser because it's cleared from the output buffer using ob_end_clean().

In your case, using ob_start() at the beginning of your script and ob_end_clean() before PDF generation ensures that any content or whitespace generated before the PDF generation process does not interfere with the PDF output. It provides a clean environment for generating the PDF without "Data has already been sent to output" errors. -->
